import type { GeneratorKey, Generator, Upgrade, StaffMember } from "./types";

export const defaultGenerators = (): Record<GeneratorKey, Generator> => ({
  pickpocket: {
    key: "pickpocket",
    name: "Pickpockets",
    icon: "🎯",
    baseCost: 10,
    costGrowth: 1.12,
    baseProd: 0.6,
    baseHeat: 0.02,
    legal: false,
    owned: 0,
  },
  racket: {
    key: "racket",
    name: "Rackets",
    icon: "💰",
    baseCost: 120,
    costGrowth: 1.13,
    baseProd: 6,
    baseHeat: 0.06,
    legal: false,
    owned: 0,
  },
  club: {
    key: "club",
    name: "Boîtes de nuit",
    icon: "🍸",
    baseCost: 1600,
    costGrowth: 1.14,
    baseProd: 40,
    baseHeat: 0.12,
    legal: false,
    owned: 0,
  },
  casino: {
    key: "casino",
    name: "Casinos",
    icon: "🎰",
    baseCost: 24000,
    costGrowth: 1.16,
    baseProd: 220,
    baseHeat: 0.22,
    legal: false,
    owned: 0,
  },
  olive: {
    key: "olive",
    name: "Huile d'olive",
    icon: "🫒",
    baseCost: 300,
    costGrowth: 1.12,
    baseProd: 4,
    baseHeat: 0.0,
    legal: true,
    owned: 0,
  },
  bar: {
    key: "bar",
    name: "Bars",
    icon: "🍷",
    baseCost: 900,
    costGrowth: 1.13,
    baseProd: 12,
    baseHeat: 0.01,
    legal: true,
    owned: 0,
  },
  grocery: {
    key: "grocery",
    name: "Épiceries",
    icon: "🛒",
    baseCost: 2200,
    costGrowth: 1.14,
    baseProd: 25,
    baseHeat: 0.005,
    legal: true,
    owned: 0,
  },
});

export const defaultUpgrades = (): Record<string, Upgrade> => ({
  u_pp_1: {
    id: "u_pp_1",
    label: "Doigts agiles",
    desc: "+100% pickpockets",
    target: "pickpocket",
    cost: 250,
    owned: false,
    mult: 2,
  },
  u_rk_1: {
    id: "u_rk_1",
    label: "Bâtons",
    desc: "+100% rackets",
    target: "racket",
    cost: 1800,
    owned: false,
    mult: 2,
  },
  u_cb_1: {
    id: "u_cb_1",
    label: "DJ maison",
    desc: "+100% boîtes",
    target: "club",
    cost: 12000,
    owned: false,
    mult: 2,
  },
  u_cs_1: {
    id: "u_cs_1",
    label: "Croupiers",
    desc: "+100% casinos",
    target: "casino",
    cost: 80000,
    owned: false,
    mult: 2,
  },
});

export function defaultStaff(): StaffMember[] {
  return [
    {
      id: "1",
      name: 'Marco "Le Rat" Rossi',
      role: "Soldat",
      family: "Famiglia d'Oro",
      stats: [80, 60, 40, 70],
    },
    {
      id: "2",
      name: 'Luca "La Main" Ferrari',
      role: "Capieri",
      family: "Famiglia del Vino",
      stats: [90, 85, 75, 95],
    },
    {
      id: "3",
      name: 'Giovanni "Blade" Conti',
      role: "Associé",
      family: "Famiglia Smeraldo",
      stats: [50, 95, 30, 45],
    },
    {
      id: "4",
      name: 'Antoine "Le Chat" Dubois',
      role: "Petite frappe",
      family: "Famiglia della Notte",
      stats: [65, 40, 55, 50],
    },
  ];
}
