const MAFIA_FIRST = [
  "Marco",
  "Luca",
  "Giovanni",
  "Alessio",
  "Vito",
  "Salvatore",
  "Rocco",
  "Franco",
  "Enzo",
  "Paolo",
  "Nico",
  "Gino",
  "Fabrizio",
  "Massimo",
  "Domenico",
  "Carlo",
  "Angelo",
  "Pietro",
  "Sergio",
  "Leonardo",
  "Antonio",
  "Giuseppe",
  "Carmine",
  "Michele",
  "Donato",
  "Gaetano",
  "Raffaele",
  "Bruno",
  "Emilio",
  "Alberto",
  "Mario",
  "Luigi",
  "Ettore",
  "Tommaso",
  "Giorgio",
  "Riccardo",
  "Silvio",
  "Claudio",
  "Umberto",
  "Adriano",
  "Renato",
  "Toni",
  "Alfonso",
  "Cosimo",
  "Pasquale",
  "Gennaro",
  "Vincenzo",
  "Pino",
  "Lorenzo",
  "Matteo",
  "Nerio",
  "Rinaldo",
  "Aldo",
  "Cesare",
  "Giuliano",
  "Dario",
  "Santino",
  "Mauro",
  "Federico",
  "Giacomo",
  "Emanuele",
];

const MAFIA_LAST = [
  "Rossi",
  "Moretti",
  "Ferrari",
  "Bianchi",
  "Conti",
  "Costa",
  "Romano",
  "Greco",
  "Gallo",
  "Barbieri",
  "Gatti",
  "Marino",
  "Giordano",
  "De Luca",
  "Lombardi",
  "Esposito",
  "Ricci",
  "De Santis",
  "Caruso",
  "Giuliani",
  "Mancini",
  "De Angelis",
  "Ruggiero",
  "Bellini",
  "Santoro",
  "Vitale",
  "Parisi",
  "Serra",
  "Palermo",
  "Caputo",
  "Giuliano",
  "De Rosa",
  "Ferretti",
  "Pellegrini",
  "Romani",
  "Leone",
  "Battaglia",
  "Benedetti",
  "Martelli",
  "Luciano",
  "Grella",
  "Corsetti",
  "Riccardi",
  "D'Amico",
  "Lombardo",
  "Siciliano",
  "Calabrese",
  "Toscano",
  "Valenti",
  "Brunetti",
  "Barone",
  "Cattaneo",
  "Fiore",
  "Sartori",
  "Capriani",
  "De Matteo",
  "Veneziano",
  "Santini",
  "Falcone",
  "Corleone",
];

const MAFIA_NICK = [
  "Le Rat",
  "La Main",
  "L'Ombre",
  "Le Chat",
  "La Griffe",
  "Il Saggio",
  "Il Toro",
  "Il Veloce",
  "Le Chacal",
  "Il Silenzio",
  "Il Muto",
  "Il Rosso",
  "Il Lupo",
  "Il Furetto",
  "Le Fantôme",
  "La Vipère",
  "Le Serpent",
  "La Mort",
  "Le Tueur",
  "Le Boss",
  "La Main Noire",
  "Le Bourreau",
  "Le Vieux",
  "Le Jeune",
  "Le Boucher",
  "Le Corbeau",
  "Le Professeur",
  "Le Traître",
  "Le Lion",
  "Le Médecin",
  "La Bête",
  "Le Sanguinaire",
  "Le Beau",
  "Le Sourd",
  "Le Noir",
  "La Flamme",
  "Le Poing",
  "Le Roi",
  "Le Fou",
  "Le Comptable",
  "Le Saint",
  "Le Marionnettiste",
  "La Lame",
  "Le Tailleur",
  "Le Jaguar",
  "Le Renard",
  "L'Araignée",
  "Le Loup Noir",
  "Le Magnifique",
  "Le Juste",
  "Le Nettoyeur",
  "Le Croque-mort",
  "Le Gentleman",
  "Le Forgeron",
  "Le Couteau",
  "Le Bâtisseur",
  "Le Fossoyeur",
  "Le Vautour",
  "Le Revenant",
  "Le Diable",
  "L'Ange Noir",
  "Le Corsaire",
  "Le Cuirassé",
  "Le Sang-Froid",
  "Le Miracle",
  "Le Solitaire",
  "Le Spectre",
  "Le Bouclier",
  "Le Goupil",
  "Le Boiteux",
  "Le Borgne",
  "Le Parfumé",
  "Le Grincheux",
  "Le Maréchal",
  "Le Consul",
  "Le Notaire",
  "Le Chanteur",
  "Le Cardinal",
  "Le Serin",
  "Le Poète",
  "Le Maudit",
  "Le Sans-Visage",
  "Le Corrompu",
  "Le Protecteur",
  "Le Froid",
  "Le Cuistot",
  "Le Négociant",
  "Le Tigre",
  "Le Vieux Loup",
  "Le Caméléon",
  "Le Duc",
  "Le Capitaine",
  "Le Moine",
  "Le Saint-Homme",
  "Le Maquignon",
  "Le Scorpion",
  "Le Grizzly",
  "Le Pèlerin",
  "Le Sommeil",
  "Le Brumeux",
  "Le Sage Fou",
];

/**
 * Génère un nom mafieux unique
 * @param existingNames Set des noms déjà utilisés pour éviter duplications
 * @returns Nom complet formaté "Prénom 'Surnom' Nom"
 */
export function generateMafiaFullName(existingNames: Set<string>): string {
  let tries = 0;
  while (tries++ < 50) {
    const f = MAFIA_FIRST[Math.floor(Math.random() * MAFIA_FIRST.length)];
    const l = MAFIA_LAST[Math.floor(Math.random() * MAFIA_LAST.length)];
    const n = MAFIA_NICK[Math.floor(Math.random() * MAFIA_NICK.length)];
    const full = `${f} "${n}" ${l}`;
    if (!existingNames.has(full)) {
      return full;
    }
  }

  // Fallback avec ID unique si toutes les combinaisons épuisées (très rare)
  const id = Math.random().toString(36).substring(2, 7).toUpperCase();
  return `${MAFIA_FIRST[0]} "Le ${id}" ${MAFIA_LAST[0]}`;
}
